#[derive(Debug, Clone, PartialEq)]
pub enum Operator {
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulus,
    Point,
    Equal,
    Clear,
    Backspace,
    Negate,
    ParenthesesOpen,
    ParenthesesClose,
    Power,
    SquareRoot,
    // Scientific
    Comma,
    Log,
    Ln,
    Log2,
    Factorial,
    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Pi,
    E,
    Reciprocal,
}

impl Operator {
    pub fn display(&self) -> &str {
        match self {
            Self::Add => "+",
            Self::Subtract => "-",
            Self::Multiply => "x",
            Self::Divide => "÷",
            Self::Modulus => "%",
            Self::Point => ".",
            Self::Equal => "=",
            Self::ParenthesesOpen => "(",
            Self::ParenthesesClose => ")",
            Self::Power => "^",
            Self::SquareRoot => "√",
            Self::Clear => "C",
            Self::Backspace => "⌫",
            Self::Negate => "±",
            // Scientific
            Self::Comma => ",",
            Self::Log => "log",
            Self::Ln => "ln",
            Self::Log2 => "log2",
            Self::Factorial => "!",
            Self::Sin => "sin",
            Self::Cos => "cos",
            Self::Tan => "tan",
            Self::Asin => "asin",
            Self::Acos => "acos",
            Self::Atan => "atan",
            Self::Pi => "π",
            Self::E => "e",
            Self::Reciprocal => "1/x",
        }
    }

    pub fn expression(&self) -> &str {
        match self {
            Self::Add => "+",
            Self::Subtract => "-",
            Self::Multiply => "*",
            Self::Divide => "/",
            Self::Modulus => "%",
            Self::Point => ".",
            Self::Equal => "=",
            Self::ParenthesesOpen => "(",
            Self::ParenthesesClose => ")",
            Self::Power => "^",
            Self::SquareRoot => "√",
            Self::Clear => "C",
            Self::Backspace => "⌫",
            Self::Negate => "±",
            Self::Comma => ",",
            Self::Log => "log",
            Self::Ln => "ln",
            Self::Log2 => "log2",
            Self::Factorial => "!",
            Self::Sin => "sin",
            Self::Cos => "cos",
            Self::Tan => "tan",
            Self::Asin => "asin",
            Self::Acos => "acos",
            Self::Atan => "atan",
            Self::Pi => "π",
            Self::E => "e",
            Self::Reciprocal => "⁻¹",
        }
    }
}