name: Pull request

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Install depencencies
        run: sudo apt-get install -y libxkbcommon-dev
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: clippy
        uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
